### ISSUE TITLE
PR/files changed issue

### ISSUE THREAD

**Issue by JamiesWhiteShirt** [Athari/CssGitHubWindows#2]
![image](https://user-images.githubusercontent.com/5446387/42347433-33a67220-80a6-11e8-93e4-69c759475dd5.png)

I made a snippet that repairs it. It's not pretty, but it gets the job done. You could use it as a reference:
```css
  .pr-toolbar.js-sticky {
    background: var(--color-button-face) !important;
  }
  .pr-toolbar.js-sticky:not(.is-stuck) {
    margin: -20px 0 0;
    padding: 0;
  }
  .pr-toolbar.js-sticky .diffbar {
    background: var(--color-button-face) !important;
  }
  .pr-toolbar.is-stuck + .pr-toolbar-shadow {
    border-bottom: solid 1px transparent !important;
    border-bottom-color: var(--button-3d-border-color) !important;
    border-top-color: var(--color-button-shadow) !important;
    height: 0;
  }
```
