### ISSUE TITLE
White header in issues and PRs

### ISSUE THREAD

**Issue by pdonias** [Athari/CssGitHubWindows#22]
![Capture_2019-04-12_17:08:38](https://user-images.githubusercontent.com/10992860/56047471-c02fde80-5d45-11e9-9a78-d717e23be64c.png)

**Comment by schumar** [comment]
Additional info: This is a `div.gh-header`, which gets assigned `background-color: #fff` in `discussion-timeline.scss`

**Comment by schumar** [comment]
Fix: Add

```css
.gh-header {
    background: var(--color-button-face) !important;
}
```
